### ISSUE TITLE
first run npm test failed

### ISSUE THREAD

**Issue by eruca** [prijs/pri#26]
I follow the guide on the official website:
1. cnpm i pri --save
2. npx pri init , select Project
3. npm test

my enviroment: macOs 10.14.3
result:
```bash
 pri test

ℹ  info      Lint and format code..
src/pages/index.tsx 299ms
tests/index.ts 19ms
ts-jest[versions] (WARN) Version 23.6.0 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=24.0.0 <25.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[versions] (WARN) Version 23.6.0 of babel-jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=24.0.0 <25.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  tests/index.ts
  ● Test suite failed to run

    ReferenceError: [BABEL] /Users/nick/Projects/breeze/alpha-pri/tests/index.ts: Unknown option: base.cwd. Check out http://babeljs.io/docs/usage/options/ for more information about options.

    A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

    Invalid:
      `{ presets: [{option: value}] }`
    Valid:
      `{ presets: [['presetName', {option: value}]] }`

    For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options.

      at Logger.error (node_modules/_babel-core@6.26.3@babel-core/lib/transformation/file/logger.js:41:11)
      at OptionManager.mergeOptions (node_modules/_babel-core@6.26.3@babel-core/lib/transformation/file/options/option-manager.js:226:20)
      at OptionManager.init (node_modules/_babel-core@6.26.3@babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/_babel-core@6.26.3@babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/_babel-core@6.26.3@babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (node_modules/_babel-core@6.26.3@babel-core/lib/transformation/pipeline.js:46:16)
      at TsJestTransformer.process (node_modules/_ts-jest@24.0.0@ts-jest/dist/ts-jest-transformer.js:110:32)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.492s
Ran all test suites.
(node:1100) UnhandledPromiseRejectionWarning: Error: Command failed: /Users/nick/Projects/breeze/alpha-pri/node_modules/_pri@2.0.67@pri/node_modules/.bin/jest --testRegex "/tests/.*\.tsx?$" --transform '{"^.+\\.tsx?$":"ts-jest"}' --moduleFileExtensions ts tsx js jsx --globals '{"ts-jest":{"babelConfig":{"presets":[["@babel/preset-env"]],"plugins":[["@babel/plugin-transform-runtime",{"regenerator":true}]]}}}' --coverage
    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:640:13)
    at Object.<anonymous> (/Users/nick/Projects/breeze/alpha-pri/node_modules/_pri@2.0.67@pri/built/built-in-plugins/command-test/plugin/run-test.js:47:25)
    at step (/Users/nick/Projects/breeze/alpha-pri/node_modules/_pri@2.0.67@pri/built/built-in-plugins/command-test/plugin/run-test.js:32:23)
    at Object.next (/Users/nick/Projects/breeze/alpha-pri/node_modules/_pri@2.0.67@pri/built/built-in-plugins/command-test/plugin/run-test.js:13:53)
    at /Users/nick/Projects/breeze/alpha-pri/node_modules/_pri@2.0.67@pri/built/built-in-plugins/command-test/plugin/run-test.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nick/Projects/breeze/alpha-pri/node_modules/_pri@2.0.67@pri/built/built-in-plugins/command-test/plugin/run-test.js:3:12)
    at Object.exports.runTest (/Users/nick/Projects/breeze/alpha-pri/node_modules/_pri@2.0.67@pri/built/built-in-plugins/command-test/plugin/run-test.js:45:40)
    at Object.<anonymous> (/Users/nick/Projects/breeze/alpha-pri/node_modules/_pri@2.0.67@pri/built/built-in-plugins/command-test/plugin/index.js:65:35)
(node:1100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ascoders** [comment]
Pri using babel@7.x, but `jest` still using `babel@6.26.3` in version `jest@23.x`. Fortunately, `jest@24.x` has upgrade babel version to `7.x`, but it not working together with [ts-jest](https://github.com/kulshekhar/ts-jest). So the only way is to fall back `jest@23.x` and try to deal with different `babel` version.

This is how i solve this problem: 

```json
{
  "postinstall": "rimraf node_modules/jest-runtime/node_modules/babel-core && rimraf node_modules/jest-config/node_modules/babel-core"
}
```

This means remove `babel-core@23.x` installed by `jest@23.x`, Unfortunately,`cnpm` has a complete different structor for `node_modules`, and `babel-core@23.x` is not in the position just mentioned.

You can try to add this to `package.json`:

```json
{
  "cnpm": {
    "mode": "npm"
  }
}
```

Or waiting `ts-jest` support `jest@24.x`, or any other suggestions?

**Comment by eruca** [comment]
I delete the project, and reset with npm, and first npm test passed.

I modify the tabWidth to 4 in .prettierrc, but I found it will be recovered to 2;
I delete the index.ts in tests, but I found it will recover too,
I add the jest.config.js to set the enzyme options, add setupTests.js in src, the npm test will promote me to delete it.

anything I did wrong?

**Comment by ascoders** [comment]
1. You can't delete project/component's entry file `index.ts`, it's a protection logic. Same as `test/index.ts`.
2. Don't allow add other config file, unless write a `pri-plugin` add to white rules:

![image](https://user-images.githubusercontent.com/7970947/54098982-04039100-43f2-11e9-87fa-7d97a56f95a8.png)

https://prijs.github.io/pri-docs/plugin/plugin-project/#whiteFileRules
